/*
 * @Author: vir virs98@outlook.com
 * @Date: 2022-11-15 23:17:33
 * @LastEditors: vir virs98@outlook.com
 * @LastEditTime: 2022-11-15 23:18:13
 */

import NextHead from "next/head";
import { FC } from "react";

const Head: FC = () => {
  return (
    <NextHead>
      <title>Stable Diffusion Tags</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </NextHead>
  );
};

export default Head;
